# Generated by Django 3.2.3 on 2021-05-31 11:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20, null=True)),
                ('lastName', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('typeUser', models.CharField(choices=[('st', 'Student'), ('te', 'Teacher')], max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            managers=[
                ('auth_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
