# Generated by Django 3.2.3 on 2021-05-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='typeUser',
            field=models.CharField(choices=[('st', 'Student'), ('te', 'Teacher')], max_length=2),
        ),
    ]
